[project]
name = "AkaneBot"
version = "0.1.0"
description = "AkaneBot"
readme = "README.md"
requires-python = ">=3.8, <4.0"

[tool.nonebot]
adapters = [
    
]
plugins = []
plugin_dirs = ["src/plugins"]
builtin_plugins = []
